"""
FineMargins — Shared Interface Contracts
==========================================
DO NOT EDIT THIS FILE without updating all three modules that depend on it.
This is the single source of truth for how pipeline/, ibm_layer/, and app/
talk to each other. Each module imports FROM here; nothing imports INTO here.

Owner: Ashish (architecture lead). If a contract needs to change mid-build,
that's a cross-cutting decision — flag it before changing, don't just edit
and hope the other two chats notice.
"""

from dataclasses import dataclass, field
from typing import Literal, Optional
from enum import Enum


# ---------------------------------------------------------------------------
# 1. PRESSURE LENS — produced by pipeline/, consumed by ibm_layer/ and app/
# ---------------------------------------------------------------------------

class Stage(str, Enum):
    GROUP = "Group Stage"
    R16 = "Round of 16"
    QF = "Quarter-finals"
    SF = "Semi-finals"
    THIRD = "3rd Place Final"
    FINAL = "Final"


@dataclass
class ShotEvent:
    """One real shot pulled from StatsBomb open data. Field names match
    StatsBomb's schema exactly (verified against real 2018/2022 WC +
    2023 WWC data) so pipeline/fetch_statsbomb.py needs no translation
    layer."""
    match_id: int
    tournament: str          # e.g. "2022 WC", "2018 WC", "WWC 2023"
    stage: str                # Stage enum value
    player: str
    team: str
    period: int                # 1,2 = halves, 3,4 = extra time, 5 = shootout
    minute: int
    is_penalty: bool
    is_shootout: bool          # period == 5
    outcome: str                # "Goal" | "Saved" | "Off T" | "Blocked" | ...
    baseline_xg: float          # StatsBomb's statsbomb_xg field


@dataclass
class PressureFeatures:
    """Engineered features for one shot, the model's actual input row."""
    minutes_remaining: float        # negative if in extra time
    score_diff: int                 # shooting team's goal diff at this moment
    stage_weight: float             # ordinal encoding, group=0 .. final/shootout=1
    is_knockout: bool
    is_shootout: bool
    is_sudden_death: bool            # shootout kick beyond round 5
    venue_neutral: bool


@dataclass
class PressureResult:
    """What pipeline/ hands back for one shot or one player-aggregate query.
    This exact shape is what ibm_layer.tools.get_pressure_profile() returns
    and what app/pages/1_pressure_lens.py renders. Don't rename fields —
    both other modules key off these names directly."""
    subject: str                       # player name or "Team X"
    sample_size: int
    baseline_conversion: float          # raw historical rate, no model
    expected_xg_rate: float             # StatsBomb baseline xG average
    pressure_adjusted_rate: float       # model's actual prediction
    pressure_delta: float               # pressure_adjusted_rate - expected_xg_rate
    confidence_interval: tuple[float, float]
    shap_top_features: list[tuple[str, float]]   # [(feature_name, contribution), ...]
    percentile_vs_field: Optional[float] = None


# ---------------------------------------------------------------------------
# 2. OFFICIATING LENS — produced/curated by ibm_layer/, consumed by app/
# ---------------------------------------------------------------------------

@dataclass
class LawCitation:
    law_number: int
    law_title: str
    excerpt: str              # PARAPHRASED summary, never verbatim IFAB text
    source_page: int           # page in the 2025/26 Laws of the Game PDF


@dataclass
class OfficiatingScenario:
    """One preloaded, real, documented incident. ibm_layer/officiating_scenarios.json
    is a list of these (as plain dicts) — app/ just reads and renders them."""
    scenario_id: str
    title: str
    tournament: str
    match: str
    minute: int
    category: Literal["penalty", "offside", "handball", "red_card", "goal_line", "discipline", "shootout"]
    description: str                      # factual, in our own words
    relevant_law: LawCitation
    historical_overturn_rate: Optional[float]   # from FIFA technical/VAR reports
    overturn_rate_source: str                    # citation string, e.g. "FIFA 2022 WC VAR report"
    what_the_model_does_not_know: list[str]


@dataclass
class NarrationRequest:
    """What app/ sends to ibm_layer.granite_client to get a Granite
    explanation. mode selects the system prompt; everything else is
    real numbers pulled from PressureResult or OfficiatingScenario —
    never free text the model could hallucinate around."""
    mode: Literal["fan", "analyst", "referee_trainee"]
    grounded_data: dict          # asdict(PressureResult) or asdict(OfficiatingScenario)
    question: Optional[str] = None


@dataclass
class NarrationResponse:
    text: str
    tool_calls_made: list[str]  # names of tools invoked (direct function calls; Context Forge gateway prototyped locally — see README)
    grounded: bool                  # True only if every number in `text` traces to a tool call


# ---------------------------------------------------------------------------
# 3. ENVIRONMENT VARIABLES — exact names, agreed once, used everywhere
# ---------------------------------------------------------------------------

REQUIRED_ENV_VARS = [
    "WATSONX_API_KEY",
    "WATSONX_PROJECT_ID",
    "WATSONX_URL",          # e.g. https://us-south.ml.cloud.ibm.com
    "WATSONX_MODEL_ID",     # e.g. ibm/granite-4-h-small — confirm exact id at build time
]

# Context Forge MCP gateway URL — prototyped locally, not wired at runtime on HF Spaces deployment.
# See ibm_layer/tools.py and README for full explanation of the deployment constraint.
CONTEXT_FORGE_LOCAL_URL = "http://127.0.0.1:4444"   # default mcpgateway port (local dev only)


# ---------------------------------------------------------------------------
# 4. FILE PATHS — agreed once, no module invents its own path scheme
# ---------------------------------------------------------------------------

PATHS = {
    "penalty_dataset": "data/processed/penalty_shap.parquet",
    "late_shots_dataset": "data/processed/late_shot_probs.parquet",
    "pressure_model": "pipeline/model_artifacts/models.pkl",
    "pressure_metrics": "pipeline/model_artifacts/metrics.json",
    "officiating_scenarios": "ibm_layer/officiating_scenarios.json",
    "law_chunks": "ibm_layer/law_chunks.json",      # Docling output, chunked IFAB text
}
